# Generated by Django 4.2 on 2023-05-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_imglink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='prodID',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='prodID',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='side',
            old_name='prodID',
            new_name='prod',
        ),
    ]
