# Generated by Django 4.2.1 on 2023-05-10 11:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
