# Generated by Django 4.2.1 on 2023-05-10 11:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_country_alter_profile_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=9999),
        ),
    ]
