# Generated by Django 4.2.1 on 2023-05-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.IntegerField(max_length=9999),
        ),
    ]
