# Generated by Django 4.2.1 on 2023-05-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_image_alter_profile_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
