# Generated by Django 4.2 on 2023-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("amountPizza", models.IntegerField()),
                ("amountSides", models.IntegerField()),
                ("amountDrinks", models.IntegerField()),
                ("price", models.FloatField()),
                ("pickup", models.BooleanField()),
                ("imgLink", models.CharField(max_length=999)),
            ],
        ),
    ]
